services:
  - type: web
    name: todo-backend
    env: node
    buildCommand: cd "TodoApp Backend" && npm install
    startCommand: cd "TodoApp Backend" && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false

  - type: web
    name: todo-frontend
    env: static
    buildCommand: cd "TodoApp Frontend" && npm install && npm run build
    staticPublishPath: ./TodoApp Frontend/dist
    envVars:
      - key: VITE_API_URL
        fromService:
          name: todo-backend
          type: web
          envVarKey: RENDER_EXTERNAL_URL
        value: /api/todos